### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by KrisAphalon**

### CODE REVIEW

**Review by KarendarToNajlepszyRadny123 — APPROVED** [review]

**Review by RoseThornrime — APPROVED** [review]

**Review by koranoligatur — APPROVED** [review]

**Review by mikkielt — APPROVED** [review]

**Review by mateuszzrocevaux — APPROVED** [review]

**Comment by akrzyz** [comment]
looks good :+1:

**Review by akrzyz — APPROVED** [review]
looks good :+1:

**Review by morrymyio — COMMENTED** [review]
.

**Review by morrymyio — APPROVED** [review]

**Comment by mateuszzrocevaux** [comment]
Commits:
https://github.com/nerthus-margonem/nerthusaddon/commit/49e82aa794618e19746c9b3cb90c21f53e50b5d9
https://github.com/nerthus-margonem/nerthusaddon/commit/022ccf98a8c55e5eed3a60b0eb6d623aa5dfdfc4
are also subject to this license.

**Pull request merged**
